# Generated by Django 5.0.2 on 2024-02-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
